# Generated by Django 3.2 on 2021-04-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogproject_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogproject',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogproject',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
